### PR TITLE
Add handbookCategories to Item

### PR DESCRIPTION
**Pull request by Razzmatazzz**

### CODE REVIEW

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy to development

**Review by Shebuka — DISMISSED** [review]

**Review by GrantBirki — DISMISSED** [review]

**Comment by Razzmatazzz** [comment]
.deploy

**Review by GrantBirki — APPROVED** [review]

**Review by Shebuka — APPROVED** [review]

**Pull request merged**
