### PR TITLE
Use new translation system

### PR DESCRIPTION
**Pull request by Razzmatazzz**
Should be deployed to production in conjunction with the matching data manager PR. Changes the way translations are handled to save space and make it easier to get a list of which strings we use.

### CODE REVIEW

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Shebuka** [comment]
Why not save the `context` in the worker? We are doing `init` with the `context` every time anyway so every consequent call can simply use the context saved in the worker. Am I missing something? 🤔

**Comment by Razzmatazzz** [comment]
> 

Each request has its own context. Saving the context for every request would likely behave like a memory leak, unless I'm missing something.

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Shebuka** [comment]
> it passes the context object which includes the requestId

Exactly, so why not assign the `context` to the `worker` instance and use it directly in `getLocale`?

something like this:

```suggestion
class WorkerKV {
    constructor(kvName, dataSource) {
        this.context = null;
```

```suggestion
    async init(context) {
        this.context = context;
```

```suggestion
    getLocale(key, info) {
        if (!key) {
            return null;
        }
        const lang = this.context.util.getLang(info, context);
```

**Comment by Razzmatazzz** [comment]
Because that worker class is instantiated once for each KV we use. But a worker can respond to multiple requests simultaneously. If the worker saves every context it receives to a single variable, it will end up calling getLocale using the wrong context for some requests.

**Comment by Razzmatazzz** [comment]
To expand on this a bit more:

The overall cloudflare worker has a "data store" that basically consists of multiple instances of the WorkerKV object, one instance for each KV used in the API.

With the cloudflare worker keeping one copy of each KV for its entire runtime, we eliminate duplicate unnecessary KV reads. Once a particular KV is read, the worker holds the result in memory until that data is considered stale, and then it reads the KV again. So each cloudflare worker only reads the KVs as often as absolutely necessary.

When the cloudflare worker receives a new API request, it assigns that request a unique ID, and assigns that request ID to the context object that the GraphQL library uses (and that is available when resolving GraphQL queries). The "data store" of WorkerKV object instances is also added to the context for each request. When GraphQL is resolving a query, the WorkerKV objects use the request ID from the context object to track which requests are responsible for triggering an initial read of the KV data (if necessary). Each GraphQL query will also potentially be made in a different language.

So if the context object for a request is saved to the WorkerKV object, there is no guarantee that the correct context object will be available at that variable later in code execution. A subsequent request may have overwritten it.

**Comment by Shebuka** [comment]
Good explanation, thank you, I also now see that `loadingPromises` is an array of the request so it makes total sense.

**Comment by Razzmatazzz** [comment]
I should probably add comments that explain what's going on to help with maintainability. If I approached this repo fresh, there is a lot of stuff I'd think could be done differently and more efficiently but would actually cause errors due to the unique behavior of Cloudflare workers.

**Pull request merged**
