### PR TITLE
upgrade wrangler

### PR DESCRIPTION
**Pull request by GrantBirki**
This pull request attempts to upgrade wrangler to v2

### CODE REVIEW

**Review by Shebuka — APPROVED** [review]

**Comment by Razzmatazzz** [comment]
I'm not sure what's going wrong here. It runs and generates the schema correctly, and you can open the playground, but any actual queries fail.

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
Seems we need to use a npm gzip package instead of using the native node gzip library now for some reason.

**Comment by GrantBirki** [comment]
.deploy to development

**Comment by GrantBirki** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Review by Razzmatazzz — APPROVED** [review]

**Comment by Razzmatazzz** [comment]
.deploy

**Pull request merged**
