### PR TITLE
Add goon reports query

### PR DESCRIPTION
**Pull request by Razzmatazzz**
This is ready to go.

### CODE REVIEW

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy

**Review by Blightbuster — APPROVED** [review]

**Review by GrantBirki — APPROVED** [review]

**Comment by Razzmatazzz** [comment]
.deploy to development

**Pull request merged**
