### PR TITLE
fix use of variable as lang argument

### PR DESCRIPTION
**Pull request by Razzmatazzz**

### CODE REVIEW

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Shebuka** [comment]
Do we need to do this type of fix with all enum fields? (like `categoryNames`)

**Comment by Razzmatazzz** [comment]
I don't believe so; the lang parameter is unique because we have bespoke code that deals with it.

**Comment by Razzmatazzz** [comment]
.deploy

**Review by Shebuka — APPROVED** [review]

**Pull request merged**
