### PR TITLE
Status from kv

### PR DESCRIPTION
**Pull request by Razzmatazzz**
Pulls server status from KV instead of current broken method.

Do not deploy until we've deployed the corresponding data manager PR.

### CODE REVIEW

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Review by Shebuka — APPROVED** [review]

**Review by GrantBirki — APPROVED** [review]

**Pull request merged**
