### PR TITLE
More map data

### PR DESCRIPTION
**Pull request by Razzmatazzz**
Make boss information available for maps.

### CODE REVIEW

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy to development

**Review by GrantBirki — APPROVED** [review]

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy to development

**Review by austinhodak — APPROVED** [review]

**Comment by Razzmatazzz** [comment]
.deploy

**Pull request merged**
