### PR TITLE
Add Transits

### PR DESCRIPTION
**Pull request by Razzmatazzz**
Also adds sell item task objective.

### CODE REVIEW

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Review by Blightbuster — APPROVED** [review]

**Pull request merged**
