### PR TITLE
add normalizedName to Vendor interface

### PR DESCRIPTION
**Pull request by Razzmatazzz**

### CODE REVIEW

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy

**Review by Shebuka — APPROVED** [review]

**Pull request merged**
