### PR TITLE
add location information for lots of things

### LINKED ISSUE #121: Many objectives missing maps
For many objectives that have a specific location or locations associated with the objective, the maps property of the objective is set to an empty array. For now I've overridden this on TT using https://github.com/TarkovTracker/tarkovdata/blob/master/objective_maps.json

This is just a reminder issue for me to deal with after the wipe.

### LINKED ISSUE #123: Add GPS data for TD maps to API
The TD tarkov maps should be moved under tarkov.dev org control, and migrate the GPS data (and associations with task objectives) to the API.

### PR DESCRIPTION
**Pull request by Razzmatazzz**
Resolves #121
Resolves #123

### CODE REVIEW

**Comment by Razzmatazzz** [comment]
.deploy to development

**Review by GrantBirki — APPROVED** [review]

**Comment by Razzmatazzz** [comment]
.deploy to development

**Review by GrantBirki — APPROVED** [review]

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy

**Review by Shebuka — APPROVED** [review]

**Comment by Razzmatazzz** [comment]
.deploy

**Pull request merged**
