### PR TITLE
info for task failure conditions, penalties

### LINKED ISSUE #122: Add failed quests property to Tasks
For tasks where another Task or Tasks are marked as failed when the task is completed, add a property to the Task definition which lists the quests that would be failed. This is currently represented as the "alternatives" property on quests in TD. Additionally, the reputation failure property should be added to represent changes from failures.

### LINKED ISSUE #125: Inconsistent return type on empty Barter.requiredItems.attributes & Barter.rewardItems.attributes.
```
"requiredItems": [
{
    "attributes": []
}]
"rewardItems": [
{
    "attributes": null
}]
```

### PR DESCRIPTION
**Pull request by Razzmatazzz**
Adds two new objective types:
- `TaskObjectiveTraderStanding` requires a given trader's reputation level to be `compareMethod` relative to the given `value`.
- `TaskObjectiveUseItem` requires using an item from the `useAny` array at least `compareMethod` times relative to `count`. It may be necessary to use the item in one or more zones, indicated by the `zoneNames` field.

Adds `failConditions`, `failureOutcome`, and `restartable` to the Task type:
- `failConditions` is an array of `TaskObjective`s and when any one of them is completed, the task is failed.
- `FailureOutcome` is a `TaskRewards` type and contains the "rewards" for failing the task. This is typically loss of trader rep.
- `restartable` indicates whether a failed task can be restarted.  Most tasks are not restartable because they cannot be failed.

Must be deployed in tandem with the data manager PR or else API errors are likely.

Resolves #122 
Resolves #125

### CODE REVIEW

**Comment by Razzmatazzz** [comment]
.deploy to development

**Review by Shebuka — APPROVED** [review]

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy

**Review by GrantBirki — DISMISSED** [review]

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy to development

**Review by GrantBirki — APPROVED** [review]

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Review by GrantBirki — APPROVED** [review]

**Pull request merged**
