### PR TITLE
Update retrieved kv after 5 minutes

### PR DESCRIPTION
**Pull request by Razzmatazzz**
Currently, a worker only retrieves data from a KV once. If that worker persists, then it won't ever update the KV data. This update ensures that workers will request new KV data if the last retrieval was more than 5 minutes ago.

### CODE REVIEW

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy

**Review by GrantBirki — APPROVED** [review]

**Review by Shebuka — DISMISSED** [review]

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy

**Review by GrantBirki — APPROVED** [review]

**Pull request merged**
