### PR TITLE
Tweak cache settings

### PR DESCRIPTION
**Pull request by Razzmatazzz**
Fixes some bugs related to caching.

### CODE REVIEW

**Comment by Razzmatazzz** [comment]
.deploy to development

**Review by GrantBirki — APPROVED** [review]

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy to development

**Review by GrantBirki — APPROVED** [review]

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy to development

**Review by GrantBirki — APPROVED** [review]

**Comment by Razzmatazzz** [comment]
.deploy

**Pull request merged**
