### PR TITLE
add more item properties

### PR DESCRIPTION
**Pull request by Razzmatazzz**
Need to wait to deploy this to prod until the data manager PR is deployed to prod.

### CODE REVIEW

**Comment by Razzmatazzz** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy to development

**Review by GrantBirki — APPROVED** [review]

**Comment by GrantBirki** [comment]
.deploy to development

**Comment by GrantBirki** [comment]
.deploy to development

**Comment by Razzmatazzz** [comment]
.deploy

**Pull request merged**
